### ISSUE TITLE
Unsupported Media Type Error

### ISSUE THREAD

**Issue by oyeaussie** [FinndropStudios/BitRocket#1]
Hello,

I am trying to integrate this script into our rocketchat server and bitbucket server, The configuration looks Ok, but in the Bitbucket logs, I see this:
"POST /scm/px/pxoc.git/git-receive-pack HTTP/1.1" c.a.b.p.h.i.RequestFactoryWebHookProcessorWorker Invalid response from hook 'http://rocketserver:3000/hooks/DAFGaz495ZDcPSjdY/Mpbrm9tSJXikdTaoND5YRcCuHugvuAyxzPrb7QiyTqPNYHWr', repository ID '71', status: '415' / 'Unsupported Media Type'

I turn on debug level on the rocketchat server and dont see anything in the logs. 

Any suggestions?

Thanks,
Guru

**Comment by oyeaussie** [comment]
Hey mate!

Any suggestions on how to resolve this?

Thanks,
Guru.

**Comment by manuelbachl** [comment]
Hi there, thanks for your patience, been sick last two weeks :-(
Well, I never received this error and we're not longer using this Integration bc we don't use BitBucket anymore. But I'll try to setup the integration on our server again this evening. I'll keep you updated!

**Comment by oyeaussie** [comment]
Hello,

Sorry to hear about you being sick. i hope you are feeling better now.

Thanks for looking into this, Ill standby.

Thanks,
Guru.

**Comment by manuelbachl** [comment]
Hmm well i checked the integration on our side and don't receive any errors. Neither with cloud- nor with server-edition. Maybe its relenting to your BitBucket instance. I think you followed all the steps mentioned in readme? Looks like the integration on BitBucket-side isn't set up correctly or the BitBucket-WebHook-plugin has some issues? U tried updatng all parts?

**Comment by Seth9** [comment]
Hello,
same issue:
WARN  [WebHookProcessor:thread-1] xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  c.a.s.p.h.i.RequestFactoryWebHookProcessorWorker Invalid response from hook 'xxxxxxxxxxxx', repository ID 'xxx', status: '415' / 'Unsupported Media Type'

Stash server v3.11.1
Stash Web Post Hooks Plugin v1.1.0
RocketChat v0.37.1

**Comment by patrickpl** [comment]
I've also checked is with sample payload. Seams that is is working now. I will close the ticket now. Please reopen it if the problem still exists and provide me a sample payload. I will try to fix it soon
