### ISSUE TITLE
Enhancement: Use Native Bitbucket Server webhooks

### ISSUE THREAD

**Issue by nickbroon** [FinndropStudios/BitRocket#15]
Bitbucket Server 5.4 added native webhooks support:
https://confluence.atlassian.com/bitbucketserver/bitbucket-server-5-4-release-notes-935388966.html

This appears to have wider range of hooks points available than the "Web Post Hooks Plugin" currently used, the integration for which appears to currently be broken according to #3, and which any rate does not have the things like PR notification like the Cloud variant. The Bitbucket Server native web hooks appear to be much closer in function to the Bitbucket Cloud hooks.

**Comment by markusb237** [comment]
Please take a look at my fork of this repository.

We needed BitBucket Server 5.6 Webhook support for Rocket.Chat in our company, so I took two days and figured this out.

According to https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html I configured the messages. 

Feel free to improve this script, @manuelbachl and @thiesschneider, you're welcome to add this script to your original project.

**Comment by manuelbachl** [comment]
Hi @markusb237 Many thanks for your improvements and the opportunity to reuse your code. Maybe you'd be somehow faster than us atm - we're hard working to get all our projects clean for this year :-) If so, feel free to open a pull request ;-)

**Comment by nickbroon** [comment]
Implemented by #16
