### ISSUE TITLE
Bitbucket-Server Script seems to be broken

### ISSUE THREAD

**Issue by EugenMayer** [FinndropStudios/BitRocket#2]
Using your howto for bitbucket server i used `https://github.com/FinndropStudios/BitRocket/blob/master/BBServer_POSTReceiveHook.js` as the script, see https://goo.gl/JRZUSG to ensure we are on the same page.

In general the configuration looks like https://goo.gl/LO7kTo

when using the example curl post, i get:

```
{"success":false,"error":"error-running-script"}%
```

Pushing to my repo does not trigger anything either. I configured the bitbucket-server as described using the correct plugin and the post hook from rocket.chat: https://goo.gl/Td1bmc

**Comment by patrickpl** [comment]
Hello,
I had the same issue because of a misconfiguration of the x-xss-protection header on nginx.
I hope it helps.

Greetings,
 Patrick

**Comment by patrickpl** [comment]
Hi,

there is also an other issue with the script. are you interested in testing a fix?

Greetings

**Comment by schoeppler** [comment]
Hey,

any news for this issue?

Greetz

**Comment by patrickpl** [comment]
Hello,

Well...no. I've fixed probably a similar issue on the cloud script. Can you send me the json that is causing the issue. I'm highly interested in fixing it.

Currently I am working on fixing the push handler on the cloud script. Later I want to do some refactoring. Maybe I can merge it with the Server version. That would help to fix issues much quicker. Unfortunately I have no payload to test it with. So please send me something 😀
Greetings

**Comment by schoeppler** [comment]
Hey,

I checked it with the example payload from the rocket.chat "client".

`curl -X POST --data-urlencode 'payload={"text":"Example message","attachments":[{"title":"Rocket.Chat","title_link":"https://rocket.chat","text":"Rocket.Chat, the best open source chat","image_url":"https://rocket.chat/images/mockup.png","color":"#764FA5"}]}' https://****.de/hooks/MWwMBkErhrabmExfW/jF3mQhhX5REY5347FaEXBomkBXzBzwJ9gWJpXXdvHqbepDGK`

JSON:
`{
  "text": "Example message",
  "attachments": [
    {
      "title": "Rocket.Chat",
      "title_link": "https://rocket.chat",
      "text": "Rocket.Chat, the best open source chat",
      "image_url": "https://rocket.chat/images/mockup.png",
      "color": "#764FA5"
    }
  ]
}`

Greetz

**Comment by schoeppler** [comment]
with the example from the bitbucket addon page it works: https://confluence.atlassian.com/bitbucketserver/post-service-webhook-for-bitbucket-server-776640367.html

seems to be a communication problem between the bitbucket server and rocket.chat. If the payload would be sent correctly, rocket.chat can handle it. I tested this with curl and the example from the addon page.

**Comment by patrickpl** [comment]
ok, let's summarize:

sample rocketchat payload: OK
sample bitbucket payload: OK
real bitbucket payload: NOT OK

Is this correct?

**Comment by schoeppler** [comment]
sample rocketchat payload: NOT OK
sample bitbucket payload: OK
real bitbucket payload: I was not able to check yet, if our bitbucket server is posting the payload at all

**Comment by patrickpl** [comment]
since this is okay so far (sample rocketchat payload should never work). I would suggest to close the issue and reopen it if you manage it to send the real bb payload and you have issues. greetings
