### ISSUE TITLE
bbcloud js seems out of date

### ISSUE THREAD

**Issue by poiz** [FinndropStudios/BitRocket#8]
I get an error after sending request to webhook:
```
{
  "success": false,
  "message": "Something went wrong before processing started or the handling of this type of trigger is not implemented. Please consider to disable the trigger or send a bug report."
}
```

It seems the method parsing json out of date.

**Comment by patrickpl** [comment]
pls send me your payload. we have it here up and working. I'm currently refactoring some stuff. might me, that your message type is not updated until now. the push should work for sure

**Comment by patrickpl** [comment]
I've tested it again and I was not able to reproduce the issue. For now I will close the bug, but please reopen it if you have the payload. You can find it on the web interface of Bitbucket
